/* Additional record code for ThermostatMonitor_HeatingOnMonitor generated by the OpenModelica Compiler OpenModelica 1.12.0~7-g6d56dda. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

