/* Additional record code for Room generated by the OpenModelica Compiler OpenModelica 1.12.0~dev-969-g8d481c1. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif

#define Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_FluidConstants__desc_added 1
const char* Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_FluidConstants__desc = {
  "Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_FluidConstants", /* package_record__X */
  "Buildings.Fluid.Interfaces.ConservationEquation$vol$dynBal.Medium.FluidConstants", /* package.record_X */
  Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_FluidConstants__desc__fields
};

#define Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties__desc_added 1
const char* Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties__desc = {
  "Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties", /* package_record__X */
  "Buildings.Fluid.Interfaces.ConservationEquation$vol$dynBal.Medium.GasProperties", /* package.record_X */
  Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties__desc__fields
};

#define Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_ThermodynamicState__desc__fields[3] = {"T","X","p"};
struct record_description Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.Interfaces.ConservationEquation$vol$dynBal.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord__desc__fields
};

#define Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_FluidConstants__desc_added 1
const char* Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_FluidConstants__desc = {
  "Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_FluidConstants", /* package_record__X */
  "Buildings.Fluid.MixingVolumes.MixingVolume$vol.Medium.FluidConstants", /* package.record_X */
  Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$dynBal$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_FluidConstants__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_FluidConstants__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_FluidConstants", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$ports.Medium.FluidConstants", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc_added 1
const char* Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc = {
  "Modelica_Media_Interfaces_Types_IdealGas_FluidConstants", /* package_record__X */
  "Modelica.Media.Interfaces.Types.IdealGas.FluidConstants", /* package.record_X */
  Modelica_Media_Interfaces_Types_IdealGas_FluidConstants__desc__fields
};

#define Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$H2O__desc_added 1
const char* Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$H2O__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$H2O__desc = {
  "Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$H2O", /* package_record__X */
  "Modelica.Media.Interfaces.Types.IdealGas.FluidConstants$H2O", /* package.record_X */
  Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$H2O__desc__fields
};

#define Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc_added 1
const char* Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc__fields[26] = {"HCRIT0","SCRIT0","acentricFactor","casRegistryNumber","chemicalFormula","criticalMolarVolume","criticalPressure","criticalTemperature","deltah","deltas","dipoleMoment","hasAccurateConductivityData","hasAccurateViscosityData","hasAcentricFactor","hasCriticalData","hasDipoleMoment","hasFundamentalEquation","hasIdealGasHeatCapacity","hasLiquidHeatCapacity","hasSolidHeatCapacity","hasVapourPressureCurve","iupacName","meltingPoint","molarMass","normalBoilingPoint","structureFormula"};
struct record_description Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc = {
  "Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2", /* package_record__X */
  "Modelica.Media.Interfaces.Types.IdealGas.FluidConstants$N2", /* package.record_X */
  Modelica_Media_Interfaces_Types_IdealGas_FluidConstants$N2__desc__fields
};

#define Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$dryair__desc_added 1
const char* Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$dryair__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$dryair__desc = {
  "Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$dryair", /* package_record__X */
  "Buildings.Fluid.Interfaces.ConservationEquation$vol$dynBal.Medium.GasProperties$dryair", /* package.record_X */
  Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$dryair__desc__fields
};

#define Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$steam__desc_added 1
const char* Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$steam__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$steam__desc = {
  "Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$steam", /* package_record__X */
  "Buildings.Fluid.Interfaces.ConservationEquation$vol$dynBal.Medium.GasProperties$steam", /* package.record_X */
  Buildings_Fluid_Interfaces_ConservationEquation$vol$dynBal_Medium_GasProperties$steam__desc__fields
};

#define Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties__desc_added 1
const char* Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties__desc = {
  "Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties", /* package_record__X */
  "Buildings.Fluid.MixingVolumes.MixingVolume$vol.Medium.GasProperties", /* package.record_X */
  Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties__desc__fields
};

#define Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$dryair__desc_added 1
const char* Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$dryair__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$dryair__desc = {
  "Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$dryair", /* package_record__X */
  "Buildings.Fluid.MixingVolumes.MixingVolume$vol.Medium.GasProperties$dryair", /* package.record_X */
  Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$dryair__desc__fields
};

#define Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$steam__desc_added 1
const char* Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$steam__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$steam__desc = {
  "Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$steam", /* package_record__X */
  "Buildings.Fluid.MixingVolumes.MixingVolume$vol.Medium.GasProperties$steam", /* package.record_X */
  Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_GasProperties$steam__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$dynBal$ports.Medium.GasProperties", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$dryair__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$dryair__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$dryair__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$dryair", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$dynBal$ports.Medium.GasProperties$dryair", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$dryair__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$steam__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$steam__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$steam__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$steam", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$dynBal$ports.Medium.GasProperties$steam", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_GasProperties$steam__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$ports.Medium.GasProperties", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$dryair__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$dryair__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$dryair__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$dryair", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$ports.Medium.GasProperties$dryair", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$dryair__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$steam__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$steam__desc__fields[4] = {"MM","R","cp","cv"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$steam__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$steam", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$ports.Medium.GasProperties$steam", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_GasProperties$steam__desc__fields
};

#define Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_ThermodynamicState__desc_added 1
const char* Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_ThermodynamicState__desc__fields[3] = {"T","X","p"};
struct record_description Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_ThermodynamicState__desc = {
  "Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_ThermodynamicState", /* package_record__X */
  "Buildings.Fluid.MixingVolumes.MixingVolume$vol.Medium.ThermodynamicState", /* package.record_X */
  Buildings_Fluid_MixingVolumes_MixingVolume$vol_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_ThermodynamicState__desc__fields[3] = {"T","X","p"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$dynBal$ports.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$dynBal$ports_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_ThermodynamicState__desc_added 1
const char* Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_ThermodynamicState__desc__fields[3] = {"T","X","p"};
struct record_description Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_ThermodynamicState__desc = {
  "Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_ThermodynamicState", /* package_record__X */
  "Modelica.Fluid.Vessels.BaseClasses.VesselFluidPorts_b$vol$ports.Medium.ThermodynamicState", /* package.record_X */
  Modelica_Fluid_Vessels_BaseClasses_VesselFluidPorts__b$vol$ports_Medium_ThermodynamicState__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Air__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Air__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Air__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Air", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Air", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Air__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Ar__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Ar__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Ar__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Ar", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Ar", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Ar__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H2_vinylidene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H2__vinylidene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H4", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H4", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H4__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H5OH", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H5OH", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H5OH__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C2H6", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C2H6", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C2H6__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C3H6_propylene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C3H6__propylene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C3H8", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C3H8", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C3H8__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C4H10_n_butane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C4H10__n__butane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C4H8_1_butene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C4H8__1__butene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C5H10_1_pentene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C5H10__1__pentene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C5H12_n_pentane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C5H12__n__pentane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H12_1_hexene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H12__1__hexene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H14_n_hexane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H14__n__hexane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C6H6", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C6H6", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C6H6__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C7H14_1_heptene", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C7H14__1__heptene__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C7H16_n_heptane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C7H16__n__heptane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C8H10_ethylbenz", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C8H10__ethylbenz__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$C8H18_n_octane", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$C8H18__n__octane__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CH3OH", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CH3OH", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CH3OH__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CH4__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CH4__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CH4__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CH4", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CH4", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CH4__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CL2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CL2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CL2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CL2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CL2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CL2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CO__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CO__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CO__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CO", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CO", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CO__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$CO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$CO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$CO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$CO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$CO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$CO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$F2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$F2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$F2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$F2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$F2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$F2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$H2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$H2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$H2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$H2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$H2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$H2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$H2O__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$H2O__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$H2O__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$H2O", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$H2O", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$H2O__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$He__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$He__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$He__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$He", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$He", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$He__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$N2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$N2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$N2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$N2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$N2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$N2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$N2O__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$N2O__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$N2O__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$N2O", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$N2O", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$N2O__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NH3__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NH3__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NH3__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NH3", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NH3", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NH3__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NO__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NO__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NO__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NO", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NO", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NO__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$NO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$NO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$NO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$NO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$NO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$NO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$Ne__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$Ne__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$Ne__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$Ne", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$Ne", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$Ne__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$O2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$O2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$O2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$O2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$O2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$O2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$SO2__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$SO2__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$SO2__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$SO2", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$SO2", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$SO2__desc__fields
};

#define Modelica_Media_IdealGases_Common_DataRecord$SO3__desc_added 1
const char* Modelica_Media_IdealGases_Common_DataRecord$SO3__desc__fields[10] = {"H0","Hf","MM","R","Tlimit","ahigh","alow","bhigh","blow","name"};
struct record_description Modelica_Media_IdealGases_Common_DataRecord$SO3__desc = {
  "Modelica_Media_IdealGases_Common_DataRecord$SO3", /* package_record__X */
  "Modelica.Media.IdealGases.Common.DataRecord$SO3", /* package.record_X */
  Modelica_Media_IdealGases_Common_DataRecord$SO3__desc__fields
};

#ifdef __cplusplus
}
#endif

